# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4e3e4661478189eee341e558c8fff202b18abbaa00ef31b55365dcac9b066b7c01454b10e8415aacc3b830d9da4a2cb19b6813446c2e3ee86885ded9fa89dd2f

test:
  secret_key_base: f08c1a617d567dd388f0e067ff2e445c69842035e2e6f54fe5861c20b505c72b883093ed5df41b4f91ffe0a181423b95b578c0073f7ceaa88796d95be3abf5d6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
